/* Report page charts, built from pre-computed numbers (see scripts/
   compute_report_stats.ps1 and rank_consistent_gainers.ps1 for how every
   figure below was derived from data/sp500_nasdaq100_weekly_prices.csv). */
(function () {
  const COLORS = {
    sp: "#3987e5", spSoft: "rgba(57,135,229,0.35)",
    ndx: "#d95926", ndxSoft: "rgba(217,89,38,0.35)",
    both: "#9085e9",
    good: "#0ca30c", critical: "#e66767", warning: "#fab219",
    grid: "#2c2c2a", axis: "#898781", text: "#c3c2b7", cross: "rgba(255,255,255,0.35)"
  };
  window.REPORT_COLORS = COLORS;   // mutated by js/theme.js when the theme changes

  const FIX_SERIES = [["2021-09-27",74.06],["2021-11-01",99.02],["2021-12-27",98.94],["2022-02-28",85.0],["2022-04-25",84.42],["2022-06-13",75.33],["2022-07-25",105.66],["2022-09-26",97.33],["2022-10-24",121.5],["2022-11-28",126.0],["2022-12-26",115.08],["2023-01-30",122.33],["2023-02-27",151.04],["2023-03-27",145.96],["2023-04-24",149.49],["2023-05-29",154.86],["2023-06-26",164.2],["2023-07-31",177.51],["2023-08-28",185.96],["2023-09-25",170.41],["2023-10-30",187.81],["2023-11-27",196.61],["2023-12-25",205.67],["2024-01-29",231.29],["2024-02-26",314.43],["2024-03-25",317.71],["2024-04-29",315.03],["2024-05-27",327.34],["2024-06-24",304.12],["2024-07-29",306.18],["2024-08-26",353.52],["2024-09-30",402.53],["2024-10-28",392.31],["2024-11-25",493.27],["2024-12-30",448.55],["2025-01-27",436.75],["2025-02-24",363.33],["2025-03-31",296.51],["2025-04-28",432.10],["2025-05-26",478.23],["2025-06-30",540.98],["2025-07-28",695.30],["2025-08-25",703.38],["2025-09-29",818.01],["2025-10-27",965.58],["2025-11-24",976.94],["2025-12-29",1003.64],["2026-01-26",1142.10],["2026-02-23",1429.37],["2026-03-30",1417.19],["2026-04-27",1867.02],["2026-05-25",1828.21],["2026-06-29",1741.30],["2026-07-27",1729.69],["2026-08-31",1610.34],["2026-09-25",1658.91]];

  const MU_SERIES = [["2021-09-27",70.99],["2021-11-08",77.30],["2021-12-27",93.15],["2022-02-14",90.80],["2022-04-04",72.14],["2022-05-30",69.94],["2022-07-25",61.86],["2022-09-19",50.10],["2022-11-14",58.58],["2023-01-09",56.93],["2023-03-06",54.93],["2023-04-24",64.36],["2023-06-19",65.28],["2023-08-14",63.59],["2023-10-16",67.22],["2023-12-11",81.41],["2024-02-05",85.56],["2024-03-18",110.21],["2024-04-29",114.70],["2024-06-10",141.36],["2024-07-29",92.70],["2024-09-16",90.90],["2024-11-11",96.34],["2024-12-30",89.87],["2025-02-24",93.63],["2025-03-31",64.72],["2025-05-19",93.37],["2025-06-30",122.29],["2025-08-25",119.01],["2025-09-29",187.83],["2025-11-10",246.83],["2025-12-29",315.42],["2026-01-26",414.88],["2026-02-23",412.37],["2026-03-30",366.24],["2026-05-04",746.81],["2026-06-15",1133.99],["2026-07-13",848.95],["2026-08-24",932.86],["2026-09-25",1082.28]];

  const BE_SERIES = [["2021-09-27",18.47],["2021-11-08",34.15],["2021-12-27",21.93],["2022-02-14",18.35],["2022-04-04",22.55],["2022-05-30",18.22],["2022-07-25",20.23],["2022-09-19",21.36],["2022-11-14",21.06],["2023-01-09",23.17],["2023-03-06",20.12],["2023-04-24",16.65],["2023-06-19",15.44],["2023-08-14",14.49],["2023-10-16",11.31],["2023-12-11",14.20],["2024-02-05",11.53],["2024-03-18",9.87],["2024-04-29",11.80],["2024-06-10",14.33],["2024-07-29",11.79],["2024-09-16",10.91],["2024-11-11",21.14],["2024-12-30",24.32],["2025-02-24",24.02],["2025-03-31",16.60],["2025-05-19",19.48],["2025-06-30",24.24],["2025-08-25",52.94],["2025-09-29",90.29],["2025-11-10",111.89],["2025-12-29",98.69],["2026-01-26",151.37],["2026-02-23",155.67],["2026-03-30",135.63],["2026-05-04",261.03],["2026-06-15",328.91],["2026-07-13",214.96],["2026-08-24",210.77],["2026-09-25",288.70]];

  // Shared interaction styling: dark tooltips, white outline on the hovered bar, smooth transitions.
  Chart.defaults.animation.duration = 700;
  Chart.defaults.datasets.bar.hoverBorderColor = "#ffffff";
  Chart.defaults.datasets.bar.hoverBorderWidth = 2;
  Object.assign(Chart.defaults.plugins.tooltip, {
    backgroundColor: "#0b0d14", borderColor: "rgba(255,255,255,0.18)", borderWidth: 1, padding: 12, cornerRadius: 8,
    titleFont: { family: "JetBrains Mono, monospace", size: 12, weight: "700" }, bodyFont: { size: 12 }, footerFont: { size: 11, weight: "400" },
    footerColor: "#898781", bodySpacing: 4
  });
  // Opens a ticker in the dashboard's Stock Explorer (same deep link the ticker tape uses).
  const openTicker = t => { window.location.href = "dashboard.html?ticker=" + encodeURIComponent(t); };
  const pointer = (evt, els) => { evt.native.target.style.cursor = els.length ? "pointer" : "default"; };

  // Growth of $10,000 (equal-weighted, buy-and-hold) - generated by scripts/compute_growth_of_10k.ps1 into data/growth_of_10k.csv.
  const GROWTH = {
    dates: ["2021-09-27","2021-10-04","2021-10-11","2021-10-18","2021-10-25","2021-11-01","2021-11-08","2021-11-15","2021-11-22","2021-11-29","2021-12-06","2021-12-13","2021-12-20","2021-12-27","2022-01-03","2022-01-10","2022-01-17","2022-01-24","2022-01-31","2022-02-07","2022-02-14","2022-02-21","2022-02-28","2022-03-07","2022-03-14","2022-03-21","2022-03-28","2022-04-04","2022-04-11","2022-04-18","2022-04-25","2022-05-02","2022-05-09","2022-05-16","2022-05-23","2022-05-30","2022-06-06","2022-06-13","2022-06-20","2022-06-27","2022-07-04","2022-07-11","2022-07-18","2022-07-25","2022-08-01","2022-08-08","2022-08-15","2022-08-22","2022-08-29","2022-09-05","2022-09-12","2022-09-19","2022-09-26","2022-10-03","2022-10-10","2022-10-17","2022-10-24","2022-10-31","2022-11-07","2022-11-14","2022-11-21","2022-11-28","2022-12-05","2022-12-12","2022-12-19","2022-12-26","2023-01-02","2023-01-09","2023-01-16","2023-01-23","2023-01-30","2023-02-06","2023-02-13","2023-02-20","2023-02-27","2023-03-06","2023-03-13","2023-03-20","2023-03-27","2023-04-03","2023-04-10","2023-04-17","2023-04-24","2023-05-01","2023-05-08","2023-05-15","2023-05-22","2023-05-29","2023-06-05","2023-06-12","2023-06-19","2023-06-26","2023-07-03","2023-07-10","2023-07-17","2023-07-24","2023-07-31","2023-08-07","2023-08-14","2023-08-21","2023-08-28","2023-09-04","2023-09-11","2023-09-18","2023-09-25","2023-10-02","2023-10-09","2023-10-16","2023-10-23","2023-10-30","2023-11-06","2023-11-13","2023-11-20","2023-11-27","2023-12-04","2023-12-11","2023-12-18","2023-12-25","2024-01-01","2024-01-08","2024-01-15","2024-01-22","2024-01-29","2024-02-05","2024-02-12","2024-02-19","2024-02-26","2024-03-04","2024-03-11","2024-03-18","2024-03-25","2024-04-01","2024-04-08","2024-04-15","2024-04-22","2024-04-29","2024-05-06","2024-05-13","2024-05-20","2024-05-27","2024-06-03","2024-06-10","2024-06-17","2024-06-24","2024-07-01","2024-07-08","2024-07-15","2024-07-22","2024-07-29","2024-08-05","2024-08-12","2024-08-19","2024-08-26","2024-09-02","2024-09-09","2024-09-16","2024-09-23","2024-09-30","2024-10-07","2024-10-14","2024-10-21","2024-10-28","2024-11-04","2024-11-11","2024-11-18","2024-11-25","2024-12-02","2024-12-09","2024-12-16","2024-12-23","2024-12-30","2025-01-06","2025-01-13","2025-01-20","2025-01-27","2025-02-03","2025-02-10","2025-02-17","2025-02-24","2025-03-03","2025-03-10","2025-03-17","2025-03-24","2025-03-31","2025-04-07","2025-04-14","2025-04-21","2025-04-28","2025-05-05","2025-05-12","2025-05-19","2025-05-26","2025-06-02","2025-06-09","2025-06-16","2025-06-23","2025-06-30","2025-07-07","2025-07-14","2025-07-21","2025-07-28","2025-08-04","2025-08-11","2025-08-18","2025-08-25","2025-09-01","2025-09-08","2025-09-15","2025-09-22","2025-09-29","2025-10-06","2025-10-13","2025-10-20","2025-10-27","2025-11-03","2025-11-10","2025-11-17","2025-11-24","2025-12-01","2025-12-08","2025-12-15","2025-12-22","2025-12-29","2026-01-05","2026-01-12","2026-01-19","2026-01-26","2026-02-02","2026-02-09","2026-02-16","2026-02-23","2026-03-02","2026-03-09","2026-03-16","2026-03-23","2026-03-30","2026-04-06","2026-04-13","2026-04-20","2026-04-27","2026-05-04","2026-05-11","2026-05-18","2026-05-25","2026-06-01","2026-06-08","2026-06-15","2026-06-22","2026-06-29","2026-07-06","2026-07-13","2026-07-20","2026-07-27","2026-08-03","2026-08-04","2026-08-10","2026-08-17","2026-08-24","2026-08-31","2026-09-07","2026-09-14","2026-09-21","2026-09-25"],
    sp500Top25: [10000,10149,10304,10491,10480,11196,11274,11096,10905,10805,11206,11088,11551,11726,11664,11755,10818,10785,11074,11218,11183,11160,10960,10929,11517,11764,11719,11501,11428,11173,10989,11361,11079,10876,11653,11528,11138,10044,10427,10099,10297,10329,10597,11356,11277,11874,11779,11476,11027,11424,10800,10276,10225,10673,10444,11154,11744,11884,12085,12150,12384,12357,11901,11770,11877,11840,12050,12469,12409,12789,12756,12888,12850,12883,13140,12649,12553,12763,13380,12956,13193,12961,13149,12923,13061,13469,13945,14076,14179,14610,14401,15013,14872,15102,15336,15516,15752,15996,15766,15970,16648,16577,16308,16047,16162,16070,16205,15687,15573,16498,16759,17058,17183,17107,17124,17765,18015,18048,17911,18437,18701,19030,19809,20396,20665,21439,22938,23130,22837,24109,24153,24957,23962,22642,23924,24143,25272,25564,26589,26121,25777,26628,26727,26291,26599,27036,25471,25277,24359,24948,26472,27016,27023,24470,26561,27991,28479,29521,30063,30170,29297,29042,32054,31007,32697,32502,32590,31673,30880,31129,32249,32114,33818,35667,32510,33334,33005,31626,30657,28230,28816,29437,28038,24218,26759,26895,29179,30809,30899,33835,33348,33927,35491,35366,36146,38238,38704,39116,39831,40977,40936,41438,40912,40782,41168,41945,43939,45038,45027,45968,45157,46217,48527,49513,49316,48068,46266,49659,49199,48836,48911,49889,50601,50555,52765,52636,53749,56416,58230,60110,59600,55896,57500,57092,56647,58843,63693,66385,68372,71114,74923,75404,75189,78718,76826,79941,84311,80401,76968,79892,74868,77499,76380,77709,77709,81984,77468,76385,78793,79046,78604,79707,79707],
    sp500All: [10000,10096,10290,10486,10477,10724,10747,10632,10412,10274,10599,10454,10678,10835,10694,10681,10101,10107,10268,10226,10095,10188,10127,9871,10381,10531,10544,10457,10384,10152,9820,9799,9612,9392,10012,9881,9401,8725,9200,9076,9137,9061,9337,9748,9755,10149,10043,9741,9435,9809,9356,8849,8653,8870,8711,9087,9593,9488,9951,9884,10072,10154,9814,9641,9676,9648,9854,10084,9959,10155,10272,10191,10187,9955,10126,9572,9446,9539,9943,9828,9954,9961,9974,9888,9822,9906,9840,10016,10127,10362,10152,10501,10415,10671,10812,10856,10719,10692,10431,10452,10703,10553,10502,10234,10196,10118,10166,9915,9717,10280,10271,10552,10662,10846,10820,11192,11266,11313,11171,11289,11373,11506,11689,11903,11995,12195,12454,12661,12561,12785,12953,12808,12440,12093,12439,12421,12735,12914,12879,12757,12641,12713,12874,12762,12781,13122,12939,12948,12612,12635,13052,13300,13310,12741,13231,13513,13641,13715,13893,14012,13724,13472,14252,13967,14515,14626,14578,14216,13772,13808,13868,13653,14226,14504,14232,14319,14427,14156,14030,13538,13333,13455,13249,12032,12626,12654,13138,13545,13577,14327,13883,14053,14280,14148,14230,14624,14917,14849,14944,15230,14900,15017,15113,15283,15292,15318,15580,15720,15718,15980,15536,15792,16103,16028,15914,15725,15424,16070,16127,16129,16107,16286,16218,16529,16717,16641,16627,17020,17151,17383,17438,16772,16566,16302,16209,16651,17241,17865,17965,18160,18419,18354,18667,18961,18719,19056,19254,19089,18998,19120,18624,18794,18707,19231,19231,19657,19138,18994,19059,18891,18663,18793,18793],
    nasdaqTop25: [10000,10080,10311,10528,10742,11226,11443,11406,11141,11166,11520,11248,11747,11808,11281,11363,10275,10203,10601,10457,10310,10399,10138,9786,10547,10812,10738,10502,10283,9990,9665,9596,9476,9049,9878,9720,9120,8542,9140,8621,9059,9057,9253,9682,9915,10136,9873,9496,9087,9537,8976,8504,8391,8543,8161,8638,9105,8780,9479,9425,9550,9526,9234,8964,8744,8734,8902,9175,9212,9630,9803,9684,9699,9464,9627,9316,9645,9774,10108,9892,10022,9981,10018,10092,10295,10782,11445,11447,11503,11842,11545,11869,11627,12048,12032,12448,12242,12028,11881,12039,12590,12371,12191,11941,12041,12293,12505,12053,11765,12569,13082,13142,13258,13267,13185,14034,14104,14136,13711,14342,15089,15222,15422,16020,15949,16064,17078,16952,16559,17339,17362,17314,17229,16089,17124,17135,17694,18157,18778,18340,18785,19908,19824,19613,20172,20345,18978,18450,17385,17896,19103,19414,19289,17650,19271,19965,20342,20844,21272,21184,21192,20722,22711,21670,22431,22636,23651,23271,22625,22834,23233,23054,24012,24887,23940,24817,26198,24713,23016,21524,21661,21736,20701,18197,20383,20026,21693,22816,22791,24704,24315,25154,25754,25636,25643,26637,26999,27158,27756,28159,28007,29423,28968,28391,28501,29129,31108,32268,32257,33597,32336,33730,34619,35829,34975,34211,32619,35272,36235,35506,36190,36678,35968,37030,37107,36953,36844,36298,36556,36952,36876,36051,36479,36208,34523,35924,38644,41391,43004,43926,47389,47358,48179,51854,49372,52225,56487,52593,51269,52451,48540,49241,48360,49806,49806,51866,49616,49375,50142,49161,49828,52037,52037],
    nasdaqAll: [10000,10056,10287,10467,10587,10991,11054,10977,10594,10397,10693,10466,10829,10869,10357,10350,9621,9532,9766,9655,9496,9601,9428,9055,9761,9888,9965,9716,9559,9222,8929,8772,8649,8388,8952,8857,8396,7883,8426,8127,8380,8290,8558,8907,9132,9387,9142,8792,8487,8889,8410,7982,7838,8001,7714,8104,8489,8207,8819,8736,8843,9008,8727,8532,8422,8419,8598,8865,8827,9139,9281,9167,9234,8969,9184,8781,8985,9071,9417,9256,9339,9341,9351,9340,9344,9587,9758,9863,9879,10196,9984,10257,10106,10501,10524,10704,10442,10382,10158,10279,10635,10539,10449,10188,10196,10268,10333,10064,9836,10458,10691,10923,11019,11150,11108,11601,11666,11715,11400,11679,11972,12054,12158,12451,12368,12471,12911,12839,12738,13064,13105,12952,12771,12145,12610,12671,12872,13147,13309,13201,13368,13687,13784,13742,13994,14142,13712,13454,12949,13180,13764,13985,13894,13074,13830,14102,14309,14438,14750,14722,14642,14425,15474,15055,15662,15729,16015,15787,15262,15287,15370,15106,15786,16082,15867,16175,16700,16084,15481,14944,14760,14906,14537,13159,14112,14062,14875,15462,15496,16407,16046,16321,16664,16646,16594,17123,17420,17309,17523,17714,17415,17946,17896,17854,17759,17918,18366,18825,18685,19201,18567,19053,19432,19701,19167,18880,18267,19262,19645,19349,19432,19600,19256,19811,19664,19631,19428,19099,19136,19377,19447,19069,18860,18644,18078,18688,19490,20599,21119,21430,22369,22216,22661,23636,22734,23581,24568,23464,23382,23752,22531,22583,22525,23339,23339,23903,23295,23188,23182,22742,22798,23549,23549]
  };


  function baseOpts(extra) {
    return Object.assign({
      responsive: true, maintainAspectRatio: false,
      plugins: { legend: { display: false } }
    }, extra);
  }
  function axisColor(scaleExtra) {
    return Object.assign({ grid: { color: COLORS.grid }, ticks: { color: COLORS.axis, font: { size: 10 } } }, scaleExtra || {});
  }

  // Vertical crosshair that follows the hovered point on line charts.
  const crosshair = {
    id: "crosshair",
    afterDatasetsDraw(chart) {
      const active = chart.tooltip && chart.tooltip.getActiveElements();
      if (!active || !active.length) return;
      const x = active[0].element.x, { top, bottom } = chart.chartArea, ctx = chart.ctx;
      ctx.save();
      ctx.strokeStyle = COLORS.cross; ctx.setLineDash([4, 4]); ctx.lineWidth = 1;
      ctx.beginPath(); ctx.moveTo(x, top); ctx.lineTo(x, bottom); ctx.stroke();
      ctx.restore();
    }
  };

  // Price line chart with a hover crosshair and 1Y / 2Y / All range buttons.
  // The tooltip shows the date, the close, and the change since the start of the visible range.
  function lineChart(id, series, color, label) {
    const canvas = document.getElementById(id);
    const lastDate = new Date(series[series.length - 1][0]);
    const slice = years => {
      if (!years) return series;
      const cut = new Date(lastDate); cut.setFullYear(cut.getFullYear() - years);
      return series.filter(p => new Date(p[0]) >= cut);
    };
    let view = series;
    const chart = new Chart(canvas, {
      type: "line",
      plugins: [crosshair],
      data: {
        labels: series.map(p => p[0]),
        datasets: [{ data: series.map(p => p[1]), borderColor: color, backgroundColor: color + "22",
          fill: true, borderWidth: 2, pointRadius: 0, pointHoverRadius: 6, pointHoverBackgroundColor: color,
          pointHoverBorderColor: "#fff", pointHoverBorderWidth: 2, tension: 0.2 }]
      },
      options: baseOpts({
        interaction: { mode: "index", intersect: false },
        plugins: { legend: { display: false }, tooltip: { displayColors: false, callbacks: {
          title: items => `${label} · week of ${items[0].label}`,
          label: ctx => `Close: $${ctx.raw.toFixed(2)}`,
          afterLabel: ctx => {
            const chg = (ctx.raw / view[0][1] - 1) * 100;
            return `${chg >= 0 ? "+" : "−"}${Math.abs(chg).toFixed(0)}% since ${view[0][0]}`;
          }
        } } },
        scales: { x: { ticks: { color: COLORS.axis, maxTicksLimit: 7, font: { size: 9 } }, grid: { display: false },
                       title: { display: true, text: "Week", color: COLORS.axis, font: { size: 10 } } },
                  y: { ...axisColor(), title: { display: true, text: "Closing price (US$)", color: COLORS.axis, font: { size: 10 } },
                       ticks: { color: COLORS.axis, font: { size: 9 }, callback: v => "$" + v } } }
      })
    });

    const bar = document.createElement("div");
    bar.className = "range-btns";
    [["1Y", 1], ["2Y", 2], ["All", 0]].forEach(([text, yrs]) => {
      const b = document.createElement("button");
      b.type = "button"; b.textContent = text;
      if (!yrs) b.classList.add("active");
      b.addEventListener("click", () => {
        bar.querySelectorAll("button").forEach(x => x.classList.toggle("active", x === b));
        view = slice(yrs);
        chart.data.labels = view.map(p => p[0]);
        chart.data.datasets[0].data = view.map(p => p[1]);
        chart.update();
      });
      bar.appendChild(b);
    });
    canvas.parentNode.parentNode.insertBefore(bar, canvas.parentNode);
  }

  // Writes each bar's value at its tip, so readers don't have to read it off the axis.
  // Enabled per chart with options.plugins.valueLabels = { fmt: value => text }.
  Chart.register({
    id: "valueLabels",
    afterDatasetsDraw(chart, args, opts) {
      if (!opts || !opts.fmt) return;
      const ctx = chart.ctx;
      const horizontal = chart.options.indexAxis === "y";
      ctx.save();
      ctx.font = "700 12px 'JetBrains Mono', monospace";
      ctx.fillStyle = COLORS.text;
      chart.data.datasets.forEach((ds, di) => {
        chart.getDatasetMeta(di).data.forEach((bar, i) => {
          const v = ds.data[i];
          if (v === null || v === undefined) return;
          const text = opts.fmt(v);
          if (horizontal) {
            ctx.textAlign = "left"; ctx.textBaseline = "middle";
            ctx.fillText(text, bar.x + 8, bar.y);
          } else {
            ctx.textAlign = "center"; ctx.textBaseline = v < 0 ? "top" : "bottom";
            ctx.fillText(text, bar.x, bar.y + (v < 0 ? 6 : -6));
          }
        });
      });
      ctx.restore();
    }
  });

  // Ticker lists behind the bar charts (from data/*_top25_consistent_gainers.csv, best score first).
  const OVERLAP_TICKERS = [
    ["FIX","HWM","MCK","EME","CAH","PWR","MPC","TRGP","IBKR","GE","ANET","VST","LLY","FLEX","APH","DELL","LITE","VLO","CAT","JBL"],
    ["CEG","KLAC","LRCX","PANW","AMD","PLTR","VRTX","WMT","AMAT","CRWD","MRVL","GILD","AAPL","ORLY","MAR","COST","GOOGL","GOOG","CTAS","APP"],
    ["MU","STX","NVDA","WDC","AVGO"]
  ];
  const SECTOR_TICKERS = {
    "S&P 500 Top 25": {
      "Information Technology": ["MU","STX","NVDA","ANET","FLEX","WDC","APH","DELL","LITE","AVGO","JBL"],
      "Industrials": ["FIX","HWM","EME","PWR","GE","CAT"], "Energy": ["MPC","TRGP","VLO"], "Health Care": ["MCK","CAH","LLY"],
      "Utilities": ["VST"], "Financials": ["IBKR"]
    },
    "Nasdaq 100 Top 25": {
      "Information Technology": ["MU","STX","NVDA","WDC","AVGO","KLAC","LRCX","PANW","AMD","PLTR","AMAT","CRWD","MRVL","AAPL"],
      "Communication Services": ["GOOGL","GOOG","APP"], "Consumer Discretionary": ["ORLY","MAR"], "Consumer Staples": ["WMT","COST"],
      "Health Care": ["VRTX","GILD"], "Industrials": ["CTAS"], "Utilities": ["CEG"]
    }
  };
  const EXCLUDED_NAMES = {
    EA: "Electronic Arts", HONA: "Honeywell Aerospace", FDXF: "FedEx Freight", Q: "Qnity Electronics", SNDK: "Sandisk", SOLV: "Solventum",
    GEV: "GE Vernova", RDDT: "Reddit", VLTO: "Veralto", ARM: "Arm Holdings", KVUE: "Kenvue", GEHC: "GE HealthCare"
  };

  // 1. Overlap between the two Top-25 lists
  new Chart(document.getElementById("chart-overlap"), {
    type: "bar",
    data: {
      labels: ["Unique to S&P 500 Top 25", "Unique to Nasdaq 100 Top 25", "On Both Top 25 Lists"],
      datasets: [{ data: [20, 20, 5], backgroundColor: [COLORS.sp, COLORS.ndx, COLORS.both], borderRadius: 4 }]
    },
    options: baseOpts({
      indexAxis: "y",
      plugins: { legend: { display: false }, valueLabels: { fmt: v => v + " tickers" },
        tooltip: { callbacks: {
          label: ctx => `${ctx.raw} tickers`,
          afterBody: items => OVERLAP_TICKERS[items[0].dataIndex].join(", ")
        } } },
      scales: { x: axisColor({ max: 24, ticks: { color: COLORS.axis, font: { size: 10 }, stepSize: 5 } }),
                y: { grid: { display: false }, ticks: { color: COLORS.text, font: { size: 12 } } } }
    })
  });

  // 2 & 3. Case studies
  lineChart("chart-fix", FIX_SERIES, COLORS.sp, "FIX");
  lineChart("chart-mu", MU_SERIES, COLORS.ndx, "MU");

  // 4. Sector composition of each Top 25
  new Chart(document.getElementById("chart-sector"), {
    type: "bar",
    data: {
      labels: ["Information Technology", "Industrials", "Energy", "Health Care", "Communication Services", "Consumer Discretionary", "Consumer Staples", "Utilities", "Financials"],
      datasets: [
        { label: "S&P 500 Top 25", data: [11, 6, 3, 3, 0, 0, 0, 1, 1], backgroundColor: COLORS.sp, borderRadius: 3 },
        { label: "Nasdaq 100 Top 25", data: [14, 1, 0, 2, 3, 2, 2, 1, 0], backgroundColor: COLORS.ndx, borderRadius: 3 }
      ]
    },
    options: baseOpts({
      indexAxis: "y",
      interaction: { mode: "nearest", axis: "y", intersect: true },
      plugins: { legend: { display: true, position: "top", labels: { color: COLORS.text, boxWidth: 12, font: { size: 11 } } },
        tooltip: { callbacks: {
          title: items => `${items[0].dataset.label} · ${items[0].label}`,
          label: ctx => `${ctx.raw} ${ctx.raw === 1 ? "ticker" : "tickers"}`,
          afterLabel: ctx => (SECTOR_TICKERS[ctx.dataset.label][ctx.label] || []).join(", ")
        } } },
      scales: { x: axisColor({ stacked: false }), y: { grid: { display: false }, ticks: { color: COLORS.text, font: { size: 10.5 } } } }
    })
  });

  // 5. Consistency vs. raw gains scatter (labeled points)
  const spPoints = [
    { x: 5.9, y: 2140, tick: "FIX", side: "right", label: "FIX  +2,140%  ·  #1 S&P consistency" },
    { x: 12.3, y: 1463, tick: "BE", side: "left", label: "BE  +1,463%  ·  #29 (misses top 25)" },
    { x: 12.9, y: 1058, tick: "SMCI", side: "left", label: "SMCI  +1,058%  ·  #36 (misses top 25)" }
  ];
  const ndxPoints = [
    { x: 7.7, y: 1425, tick: "MU", side: "right", label: "MU  +1,425%  ·  #1 Nasdaq consistency" },
    { x: 6.6, y: 986, tick: "STX", side: "right", label: "STX  +986%  ·  #2 Nasdaq consistency" }
  ];
  // Draws each point's ticker next to its marker so readers can tell the dots apart.
  const pointLabels = {
    id: "pointLabels",
    afterDatasetsDraw(chart) {
      const ctx = chart.ctx;
      ctx.save();
      ctx.font = "700 12px 'JetBrains Mono', monospace";
      ctx.fillStyle = COLORS.text;
      ctx.textBaseline = "middle";
      chart.data.datasets.forEach((ds, di) => {
        chart.getDatasetMeta(di).data.forEach((el, i) => {
          const p = ds.data[i];
          ctx.textAlign = p.side === "left" ? "right" : "left";
          ctx.fillText(p.tick, el.x + (p.side === "left" ? -12 : 12), el.y);
        });
      });
      ctx.restore();
    }
  };
  new Chart(document.getElementById("chart-consistency-scatter"), {
    type: "scatter",
    plugins: [pointLabels],
    data: { datasets: [
      { label: "S&P 500 names", data: spPoints, backgroundColor: COLORS.spSoft, borderColor: COLORS.sp, borderWidth: 1.5, radius: 6, hoverRadius: 8 },
      { label: "Nasdaq 100 names", data: ndxPoints, backgroundColor: COLORS.ndxSoft, borderColor: COLORS.ndx, borderWidth: 1.5, radius: 6, hoverRadius: 8 }
    ] },
    options: baseOpts({
      onHover: pointer,
      onClick: (evt, els, chart) => { if (els.length) openTicker(chart.data.datasets[els[0].datasetIndex].data[els[0].index].tick); },
      plugins: { legend: { display: true, position: "top", labels: { color: COLORS.text, boxWidth: 12, font: { size: 11 } } },
                 tooltip: { callbacks: { label: ctx => ctx.raw.label, footer: () => "Click to open in the dashboard" } } },
      scales: {
        x: axisColor({ min: 5, max: 14, title: { display: true, text: "Weekly volatility (std. dev.)", color: COLORS.axis, font: { size: 10 } },
                        ticks: { color: COLORS.axis, font: { size: 9 }, callback: v => v + "%" } }),
        y: axisColor({ title: { display: true, text: "5-year cumulative return", color: COLORS.axis, font: { size: 10 } },
                        ticks: { color: COLORS.axis, font: { size: 9 }, callback: v => v + "%" } })
      }
    })
  });

  // 6. Average volatility, S&P vs Nasdaq eligible pools
  new Chart(document.getElementById("chart-volatility"), {
    type: "bar",
    data: { labels: ["S&P 500", "Nasdaq 100"],
      datasets: [
        { label: "All eligible tickers (493 S&P 500, 98 Nasdaq 100)", data: [4.46, 5.31], backgroundColor: [COLORS.spSoft, COLORS.ndxSoft], borderRadius: 4 },
        { label: "Top 25 most consistent", data: [5.48, 5.82], backgroundColor: [COLORS.sp, COLORS.ndx], borderRadius: 4 }
      ] },
    options: baseOpts({
      plugins: { legend: { display: true, position: "top", labels: { color: COLORS.text, boxWidth: 12, font: { size: 11 } } },
                 valueLabels: { fmt: v => v.toFixed(2) + "%" },
                 tooltip: { callbacks: { label: ctx => `${ctx.dataset.label}: ${ctx.raw.toFixed(2)}%` } } },
      scales: { x: { grid: { display: false }, ticks: { color: COLORS.text, font: { size: 12 } } },
                y: axisColor({ min: 0, max: 7, ticks: { color: COLORS.axis, font: { size: 10 }, stepSize: 1, callback: v => v + "%" } }) }
    })
  });

  // 7. Top 25 outperformance vs the full eligible pool
  new Chart(document.getElementById("chart-outperformance"), {
    type: "bar",
    data: {
      labels: ["S&P 500", "Nasdaq 100"],
      datasets: [
        { label: "Top 25 Consistent (avg)", data: [697.1, 420.4], backgroundColor: [COLORS.sp, COLORS.ndx], borderRadius: 4 },
        { label: "Full Eligible Pool (avg)", data: [87.9, 135.5], backgroundColor: [COLORS.spSoft, COLORS.ndxSoft], borderRadius: 4 }
      ]
    },
    options: baseOpts({
      plugins: { legend: { display: true, position: "top", labels: { color: COLORS.text, boxWidth: 12, font: { size: 11 } } },
                 valueLabels: { fmt: v => "+" + Math.round(v) + "%" } },
      scales: { x: { grid: { display: false }, ticks: { color: COLORS.text, font: { size: 12 } } },
                y: axisColor({ max: 800, ticks: { color: COLORS.axis, font: { size: 10 }, callback: v => v + "%" } }) }
    })
  });

  // 7b. Growth of $10,000, equal-weighted buy-and-hold: top 25 vs the full eligible pool, each index
  const usd = v => "$" + Math.round(v).toLocaleString("en-US");
  const growthDatasets = [
    { label: "S&P 500 top 25", data: GROWTH.sp500Top25, borderColor: COLORS.sp, borderWidth: 2.5 },
    { label: "S&P 500 all eligible", data: GROWTH.sp500All, borderColor: COLORS.sp, borderWidth: 1.5, borderDash: [5, 4] },
    { label: "Nasdaq 100 top 25", data: GROWTH.nasdaqTop25, borderColor: COLORS.ndx, borderWidth: 2.5 },
    { label: "Nasdaq 100 all eligible", data: GROWTH.nasdaqAll, borderColor: COLORS.ndx, borderWidth: 1.5, borderDash: [5, 4] }
  ].map(d => Object.assign({ pointRadius: 0, pointHoverRadius: 5, tension: 0.15, fill: false }, d));
  // Prints each visible line's ending value at its right-hand end.
  const endLabels = {
    id: "endLabels",
    afterDatasetsDraw(chart) {
      const ctx = chart.ctx;
      ctx.save();
      ctx.font = "700 11px 'JetBrains Mono', monospace"; ctx.textAlign = "left"; ctx.textBaseline = "middle";
      chart.data.datasets.forEach((ds, i) => {
        if (!chart.isDatasetVisible(i)) return;
        const pt = chart.getDatasetMeta(i).data[ds.data.length - 1];
        ctx.fillStyle = ds.borderColor;
        ctx.fillText(usd(ds.data[ds.data.length - 1]), pt.x + 8, pt.y);
      });
      ctx.restore();
    }
  };
  new Chart(document.getElementById("chart-growth"), {
    type: "line",
    plugins: [crosshair, endLabels],
    data: { labels: GROWTH.dates, datasets: growthDatasets },
    options: baseOpts({
      interaction: { mode: "index", intersect: false },
      layout: { padding: { right: 62 } },
      plugins: {
        legend: { display: true, position: "top", labels: { color: COLORS.text, boxWidth: 18, font: { size: 11 } } },
        tooltip: { itemSort: (a, b) => b.raw - a.raw, callbacks: {
          title: items => `Week of ${items[0].label}`,
          label: ctx => `${ctx.dataset.label}: ${usd(ctx.raw)}`
        } }
      },
      scales: {
        x: { ticks: { color: COLORS.axis, maxTicksLimit: 6, font: { size: 9 } }, grid: { display: false } },
        y: axisColor({ min: 0, title: { display: true, text: "Value of $10,000 invested Sep 2021", color: COLORS.axis, font: { size: 10 } },
                       ticks: { color: COLORS.axis, font: { size: 9 }, callback: v => "$" + v.toLocaleString("en-US") } })
      }
    })
  });

  // 8. Excluded tickers — weeks of history available
  new Chart(document.getElementById("chart-excluded"), {
    type: "bar",
    data: {
      labels: ["EA", "HONA", "FDXF", "Q", "SNDK", "SOLV", "GEV", "RDDT", "VLTO", "ARM", "KVUE", "GEHC"],
      datasets: [{ data: [1, 16, 19, 49, 86, 132, 132, 133, 157, 160, 179, 199], backgroundColor: COLORS.warning, borderRadius: 3, barThickness: 16 }]
    },
    options: baseOpts({
      indexAxis: "y",
      plugins: { legend: { display: false }, tooltip: { callbacks: {
        title: items => `${items[0].label} · ${EXCLUDED_NAMES[items[0].label]}`,
        label: ctx => `${ctx.raw} of 262 weeks (${(ctx.raw/262*100).toFixed(0)}%)`
      } } },
      scales: { x: axisColor({ title: { display: true, text: "Weeks of history out of 262 possible", color: COLORS.axis, font: { size: 10 } } }),
                y: { grid: { display: false }, ticks: { autoSkip: false, color: COLORS.text, font: { size: 11, family: "monospace" } } } }
    })
  });

  // 9. Most extreme single weeks in the dataset
  new Chart(document.getElementById("chart-extremes"), {
    type: "bar",
    data: {
      labels: ["INSM — Insmed, 2024-05-27", "FISV — Fiserv, 2025-10-27"],
      datasets: [{ data: [150, -47], backgroundColor: [COLORS.good, COLORS.critical], borderRadius: 6, barThickness: 70 }]
    },
    options: baseOpts({
      onHover: pointer,
      onClick: (evt, els) => { if (els.length) openTicker(["INSM", "FISV"][els[0].index]); },
      plugins: { legend: { display: false }, valueLabels: { fmt: v => (v > 0 ? "+" : "−") + Math.abs(v) + "%" },
        tooltip: { callbacks: { label: ctx => `${ctx.raw > 0 ? "+" : "−"}${Math.abs(ctx.raw)}% in one week`, footer: () => "Click to open in the dashboard" } } },
      scales: { x: { grid: { display: false }, ticks: { color: COLORS.text, font: { size: 11.5 } } },
                y: axisColor({ min: -100, max: 200, ticks: { color: COLORS.axis, font: { size: 10 }, stepSize: 50, callback: v => v + "%" } }) }
    })
  });
})();
